workflows:
  ios-app-store:
    name: Alda-Gel iOS Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Paketleri ve iOS Gereksinimlerini Yükle
        script: |
          npm install
          npm install @capacitor/ios --save-dev
      - name: Next.js Projesini Derle
        script: npm run build
      - name: iOS Platformunu Kur ve Senkronize Et
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: iOS Projesini Derle
        script: |
          WORKSPACE_PATH="ios/App/App.xcodeproj/project.xcworkspace"
          echo "Workspace yolu: $WORKSPACE_PATH"
          
          # Parametreyi çıkardık, bu haliyle kaba inşaatı bitirmeli
          xcode-project build-ipa \
            --workspace "$WORKSPACE_PATH" \
            --scheme "App"