workflows:
  ios-app-store:
    name: Alda-Gel iOS Build
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Paketleri Yükle
        script: npm install
      - name: Next.js Projesini Derle
        script: npm run build
      - name: iOS Platformunu Kur ve Senkronize Et
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: iOS Projesini Derle
        script: |
          WORKSPACE_PATH="ios/App/App.xcodeproj/project.xcworkspace"
          
          # build-ipa yerine build komutunu kullanıyoruz ki .plist hatası almayalım
          xcodebuild build \
            -workspace "$WORKSPACE_PATH" \
            -scheme "App" \
            -sdk iphoneos \
            -configuration Debug